services:
  customer-db:
    container_name: customer-db
    image: postgres:16.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db_network
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - db_network
    restart: unless-stopped
    depends_on:
      - customer-db
#  # just a containerized version of the application be
#  this-app-be-api:
#    container_name: be-api
#    image: bardiniww/generic
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://customer-db:5432/customer
#    ports:
#      - "8088:8080"
#    networks:
#      - db_network
#    depends_on:
#      - customer-db
#    restart: unless-stopped

networks:
  db_network:
    driver: bridge

volumes:
  postgres:
  pgadmin: